functions: [validateXOBFields]
rules:
  element-valid-item-type-group:
    message: 'Item type group does not exist: {{error}}'
    given: $.components.schemas[*].allOf[1][x-ob-item-type-group]
    severity: error
    then:
      function: validateXOBFields
      functionOptions:
        objectPath: x-ob-item-type-groups
